{
  "TOOLNAME": "py3-exceptiongroup",
  "TOOLVERSION": "1.1.1-db13989a6e4f885f250cba9f4a6eb6bf"
}